---
name: build-push-debian-latest

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '10 5,12 * * 1,6'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test debian-latest
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-debian-latest .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-debian-latest

  # If on bookworm branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: /
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            buluma/debian-systemd:latest, buluma/debian:latest
