name: build-push

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/bookworm'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short
        run: echo "short=${GITHUB_REF##*/}" >> "${GITHUB_ENV}"
      - name: Set tag
        run: echo "tag=${short/main/latest}" >> "${GITHUB_ENV}"
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: /
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: buluma/debian-systemd:${{ env.tag }}
